### ISSUE TITLE
Filtering step removed

### ISSUE THREAD

**Issue by even4void** [geraldinepascal/FROGS#51]
First of all, thank you for developing such a nice workflow. 

For the record, we ran into multiple issues following the (non-Galaxy) "manual install" instructions on Ubuntu 18.06 because of (1) Maven's deprecation of `http` in favor of `https`, (2) `ivy` versioning (the latest 2.5 version is required for kMer apparently), (3) minor Java JDK compatibility issues with RDPTools ((JDK8 from Oracle seems to be working at least, no need to downgrade `ant` apparently), and (4) some subtleties with `junit` version differing from the one declared in `*.pom` files. That was quite a day.

Regarding the current version, as of a recent `git checkout`, it looks like the filtering step (`filters.py`, after removing chimera) has been [removed](https://github.com/geraldinepascal/FROGS/commit/c8bc2adcd3aed3b7ec1600ad25666045b6c7232e#diff-4a931512ce65bdc9ca6808adf92d8783): How are we supposed to run the test suite ? Are we supposed to simply replace `04-filters.{fasta,biom}` input files with `03-chimera.{fasta,biom}`?

**Comment by mariabernard** [comment]
Hi,

Thank you for using FROGS!

I am aware about trouble installing rdptools 2.0.2 and all version problem you pointed out (ant, java). In fact this version of rdptools is no more installable because of the Maven URL changes.
Everything is solved with the 2.0.3 of rdptools and it works with java 1.8 and ant 1.10.5 (this is my local config) (look here for details : https://github.com/rdpstaff/RDPTools/issues/31).

I am not aware about `junit` and `*.pom`, in fact I do not known at which point we use this.

It seems that you are not installing fixed release of FROGS (last one is 3.1), the code in the master branch correspond to the future 3.2 release, but we have some (times) trouble to finalize it. In fact you are rigth filters.py will be (is) splitted into 2 tools otu-filters.py and affiliation_filters.py. 
As this version is not finallized, my advice is to install an official release (so the 3.1), and the easier way is to use conda.
`conda create --name __frogs@3.1.0 frogs=3.1.0`

I just retest it, you will maybe have some "error message" at the end that in fact are warning messages.

For docker, I do not think that we will spent some time on this field, developping, wrapping for Galaxy, maintaining the conda receipt, and training users is quite a lot for the three of us. But enough complaining. I hope this will help you to install FROGS and that you will be satisfied with your analysis.

**Comment by even4void** [comment]
Thanks for the quick reply, Maria! Indeed it sounds that it may well be a problem with me using the wrong release. I'll retry with v3.1. I try to avoid Conda as much as I can so I'll be using vanilla Python 3.

P.S. Regarding Maven and package dependencies, I got some errors with `junit-4.8.2.jar` which was expected for, e.g., AbundanceStats, while a more recent version of `junit` was already downloaded according to the `build.xml` settings probably.

**Comment by even4void** [comment]
I can confirm that it now works perfectly using v3.1!

P.S. It also works with R 4.0 and Python 3.8 on Ubuntu 20.06.
